export enum SystemRoleTypes {
  SUPER_ADMIN = 'SuperAdmin',
  ORGANIZATION_ADMIN = 'OrganizationAdmin',
  STANDARD_USER = 'StandardUser',
}

export enum SystemPermissionTypes {
  FLATFORM_ADMIN = 'FLATFORM_ADMIN',

  ADD_AUTHEN = 'ADD_AUTHEN',
  ADD_ORG = 'ADD_ORG',
  ADD_POSITION = 'ADD_POSITION',
  ADD_USER = 'ADD_USER',
  ADD_ROLE = 'ADD_ROLE',
  ADD_LOCATION = 'ADD_LOCATION',
  ADD_SUBJECT = 'ADD_SUBJECT',
  ADD_BIOMARKERS = 'ADD_BIOMARKERS',
  ADD_EVENT_TYPE = 'ADD_EVENT_TYPE',
  ADD_EVENT_DIAGNOSIS = 'ADD_EVENT_DIAGNOSIS',
  ADD_EVENT_REGIMEN = 'ADD_EVENT_REGIMEN',
  ADD_EVENT = 'ADD_EVENT',

  EDIT_AUTHEN = 'EDIT_AUTHEN',
  EDIT_ORG = 'EDIT_ORG',
  EDIT_POSITION = 'EDIT_POSITION',
  EDIT_USER = 'EDIT_USER',
  EDIT_ROLE = 'EDIT_ROLE',
  EDIT_LOCATION = 'EDIT_LOCATION',
  EDIT_SUBJECT = 'EDIT_SUBJECT',
  EDIT_BIOMARKERS = 'EDIT_BIOMARKERS',
  EDIT_EVENT_TYPE = 'EDIT_EVENT_TYPE',
  EDIT_EVENT_DIAGNOSIS = 'EDIT_EVENT_DIAGNOSIS',
  EDIT_EVENT_REGIMEN = 'EDIT_EVENT_REGIMEN',
  EDIT_EVENT = 'EDIT_EVENT',

  DELETE_AUTHEN = 'DELETE_AUTHEN',
  DELETE_ORG = 'DELETE_ORG',
  DELETE_POSITION = 'DELETE_POSITION',
  DELETE_USER = 'DELETE_USER',
  DELETE_ROLE = 'DELETE_ROLE',
  DELETE_LOCATION = 'DELETE_LOCATION',
  DELETE_SUBJECT = 'DELETE_SUBJECT',
  DELETE_BIOMARKERS = 'DELETE_BIOMARKERS',
  DELETE_EVENT_TYPE = 'DELETE_EVENT_TYPE',
  DELETE_EVENT_DIAGNOSIS = 'DELETE_EVENT_DIAGNOSIS',
  DELETE_EVENT_REGIMEN = 'DELETE_EVENT_REGIMEN',
  DELETE_EVENT = 'DELETE_EVENT',

  VIEW_AUTHEN = 'VIEW_AUTHEN',
  VIEW_DETAIL_AUTHEN = 'VIEW_DETAIL_AUTHEN',
  VIEW_ORGS = 'VIEW_ORGS',
  VIEW_DETAIL_ORG = 'VIEW_DETAIL_ORG',
  VIEW_POSITIONS = 'VIEW_POSITIONS',
  VIEW_DETAIL_POSITION = 'VIEW_DETAIL_POSITION',
  VIEW_ROLES = 'VIEW_ROLES',
  VIEW_DETAIL_ROLE = 'VIEW_DETAIL_ROLE',
  VIEW_USERS = 'VIEW_USERS',
  VIEW_DETAIL_USER = 'VIEW_DETAIL_USER',
  VIEW_LOCATIONS = 'VIEW_LOCATIONS',
  VIEW_DETAIL_LOCATION = 'VIEW_DETAIL_LOCATION',
  VIEW_SUBJECTS = 'VIEW_SUBJECTS',
  VIEW_DETAIL_SUBJECT = 'VIEW_DETAIL_SUBJECT',
  VIEW_LIST_BIOMARKERS = 'VIEW_LIST_BIOMARKERS',
  VIEW_DETAIL_BIOMARKERS = 'VIEW_DETAIL_BIOMARKERS',
  VIEW_LIST_EVENT_TYPE = 'VIEW_LIST_EVENT_TYPE',
  VIEW_DETAIL_EVENT_TYPE = 'VIEW_DETAIL_EVENT_TYPE',
  VIEW_LIST_EVENT_DIAGNOSIS = 'VIEW_LIST_EVENT_DIAGNOSIS',
  VIEW_DETAIL_EVENT_DIAGNOSIS = 'VIEW_DETAIL_EVENT_DIAGNOSIS',
  VIEW_LIST_EVENT_REGIMEN = 'VIEW_LIST_EVENT_REGIMEN',
  VIEW_DETAIL_EVENT_REGIMEN = 'VIEW_DETAIL_EVENT_REGIMEN',
  VIEW_LIST_EVENT = 'VIEW_LIST_EVENT',
  VIEW_DETAIL_EVENT = 'VIEW_DETAIL_EVENT',
  VIEW_LOT_LIST_BY_ORGANIZATION_ID = 'VIEW_LOT_LIST_BY_ORGANIZATION_ID',
  VIEW_PEN_LIST_BY_ORGANIZATION_ID = 'VIEW_PEN_LIST_BY_ORGANIZATION_ID',
  VIEW_LIST_BIOMARKERS_SUBJECT = 'VIEW_LIST_BIOMARKERS_SUBJECT',
  VIEW_EVENTS_HEALTH = 'VIEW_EVENTS_HEALTH',
  IMPORT_DATA = 'IMPORT_DATA',
}

export enum SystemRoleLevel {
  SUPER_ADMIN = 1,
  ORGANIZATION_ADMIN = 2,
  STANDARD_USER = 3,
}

export enum RequiredInTypes {
  BODY = 'body',
  QUERY = 'query',
  PARAMS = 'params',
}

export enum Sex {
  HEIFER = 'Heifer',
  STEER = 'Steer',
  COW = 'Cow',
  BULL = 'Bull',
}

export enum LocationType {
  FEED_YARD = 'Feed Yard',
  DAIRY_FARM = 'Dairy Farm',
}

export enum LightColor {
  GREEN = 'Green',
  RED = 'Red',
}
